WebApp/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult BirthForm()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result(Birth birth)
        {
            if (!birth.IsValid())
            {
                ViewBag.ErrorMessage = "Proszę podać poprawne imię i datę urodzin.";
                return View("BirthForm");
            }

            int age = birth.CalculateAge();
            ViewBag.Message = $"Cześć {birth.Name}, masz {age} lat(a).";

            return View("BirthResult");
        }
    }
}

WebApp/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class CalculatorController : Controller
{
    private readonly ILogger<CalculatorController> _logger;

    public CalculatorController(ILogger<CalculatorController> logger)
    {
        _logger = logger;
    }
    
    public enum Operator
    {
        Add, Sub, Mul, Div
    }
    [HttpPost]
    public IActionResult Result([FromForm] Calculator model)
    {
        if (!model.IsValid())
        {
            return View("Error");
        }
        else
        {
            return View(model);
        }
    }
    public IActionResult Form()
    {
        return View();
    }
}

WebApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApp.Models;

using WebApp.Models.Services;

namespace WebApp.Controllers;
[Authorize(Roles = "user")]
public class ContactController : Controller
{
    private readonly IContactService _contactService;
    public ContactController(IContactService contactService)
    {
        _contactService = contactService;
    }
    [AllowAnonymous]
    // Lista kontaków
    public IActionResult Index()
    {
        return View( _contactService.GetAll());
    }
    // Formularz dodawania
    [HttpGet]
    public IActionResult Add()
    {
        var model = new ContactModel();
        model.Organizations = _contactService.GetAllOrganizaions()
            .Select(e => new SelectListItem()
                {
                Value = e.Id.ToString(),
                Text = e.Name,
                Selected = e.Id==102
                }
            ).ToList();
        return View(model);
    }
    // odebranie danych i zapis kontaku
    [HttpPost]
    public IActionResult Add(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            model.Organizations = _contactService.GetAllOrganizaions()
                .Select(e => new SelectListItem()
                    {
                        Value = e.Id.ToString(),
                        Text = e.Name,
                        Selected = e.Id==model.Id
                    }
                ).ToList();
            return View(model);
        }
        _contactService.Add(model);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int id)
    {
        _contactService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
    [AllowAnonymous]
    public IActionResult Details(int id)
    {
        return View(_contactService.GetById(id));
    }
    public IActionResult Edit(int id)
    {
        return View(_contactService.GetById(id));
    }
    [HttpPost]
    public IActionResult Edit(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        _contactService.Update(model);
        return RedirectToAction(nameof(Index));
    }
}

WebApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models.VideoGames;
using WebApp.Helpers;


namespace WebApp.Controllers
{
    [Authorize(Roles = "user")]
    public class GameController : Controller
    {
        private readonly VideoGamesDbContext _context;

        public GameController(VideoGamesDbContext context)
        {
            _context = context;
        }
        
        [AllowAnonymous]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber, int? pageSize)
        {
            int defaultPageSize = pageSize ?? 20; // Domyślna liczba elementów na stronę
            int currentPageNumber = pageNumber ?? 1; // Ustaw bieżący numer strony
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["PageSize"] = defaultPageSize;

            var games = _context.Games
                .Include(g => g.Genre)
                .Include(g => g.GamePublishers)
                .ThenInclude(gp => gp.Publisher)
                .AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                games = games.Where(g => g.GameName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    games = games.OrderByDescending(g => g.GameName);
                    break;
                default:
                    games = games.OrderBy(g => g.GameName);
                    break;
            }

            int totalItems = await games.CountAsync();
            int maxPageNumber = (int)Math.Ceiling((double)totalItems / defaultPageSize);
            ViewData["PageNumber"] = currentPageNumber;
            ViewData["MaxPageNumber"] = maxPageNumber;

            return View(await PaginatedList<Game>.CreateAsync(games.AsNoTracking(), currentPageNumber, defaultPageSize));
        }
        [AllowAnonymous]
        public async Task<IActionResult> Search(string searchString, int? pageNumber, int? pageSize)
        {
            int defaultPageSize = pageSize ?? 20;
            int currentPageNumber = pageNumber ?? 1;
        
            ViewData["CurrentFilter"] = searchString;
            ViewData["PageSize"] = defaultPageSize;
        
            var sortedGameIds = new SortedSet<int>();
        
            if (!string.IsNullOrEmpty(searchString))
            {
                // Find publishers matching the search string
                var matchingPublisherIds = await _context.Publishers
                    .Where(p => p.PublisherName.Contains(searchString))
                    .Select(p => p.Id)
                    .ToListAsync();
        
                if (matchingPublisherIds.Any())
                {
                    // Find games associated with matching publishers
                    var publisherGameIds = await _context.GamePublishers
                        .Where(gp => matchingPublisherIds.Contains(gp.PublisherId ?? 0))
                        .Select(gp => gp.GameId ?? 0)
                        .ToListAsync();
        
                    foreach (var gameId in publisherGameIds)
                    {
                        sortedGameIds.Add(gameId);
                    }
                }
        
                // Find games matching the search string by name
                var matchingGames = await _context.Games
                    .Where(g => g.GameName.Contains(searchString))
                    .Select(g => g.Id)
                    .ToListAsync();
        
                foreach (var gameId in matchingGames)
                {
                    sortedGameIds.Add(gameId);
                }
            }
        
            // Retrieve the games based on the sortedGameIds
            var games = _context.Games
                .Include(g => g.Genre)
                .Include(g => g.GamePublishers).ThenInclude(gp => gp.Publisher)
                .Where(g => sortedGameIds.Contains(g.Id));
        
            // Pagination logic
            int totalItems = sortedGameIds.Count;
            int maxPageNumber = (int)Math.Ceiling((double)totalItems / defaultPageSize);
            ViewData["PageNumber"] = currentPageNumber;
            ViewData["MaxPageNumber"] = maxPageNumber;
        
            var paginatedGames = await PaginatedList<Game>.CreateAsync(games.AsNoTracking(), currentPageNumber, defaultPageSize);
        
            return View(paginatedGames);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "GenreName");
            return View();
        }

        // POST: Game/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameName,GenreId")] Game game)
        {
            if (ModelState.IsValid)
            {
                // Sprawdź, czy nazwa gry już istnieje
                if (_context.Games.Any(g => g.GameName == game.GameName))
                {
                    ModelState.AddModelError("GameName", "A game with this name already exists.");
                    ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "GenreName", game.GenreId);
                    return View(game);
                }
                //znajdywanie i ustawianie ID, żeby możnabyło dodać nową grę (NIE WIEM DLACZEGO SQLITE NIE INKREMENTUJE A PRZYPISUJE ID = 0)
                var maxId = _context.Games.Max(g => g.Id);  
                game.Id = maxId + 1;  
                
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "GenreName", game.GenreId);
            return View(game);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "GenreName", game.GenreId);
            return View(game);
        }

        // POST: Game/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenreId,GameName")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "GenreName", game.GenreId);
            return View(game);
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Game/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Games.FindAsync(id);
            if (game != null)
            {
                _context.Games.Remove(game);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Games.Any(e => e.Id == id);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                 
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Kalkulator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="BirthForm">Kalkulator daty urodzenia</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Kontakty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Gry</a>
                    </li>

                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/nullxy.cshtml
@{
    ViewBag.Title = "Błąd kalkulatora";
    Layout = "_Layout";
}
<h2>ERROR XD</h2>